#!/bin/sh


if [ -z $1 ]; then
  echo "Usage: $0 client|server [version]" >&2
  exit 1
fi

EDITION=$1
VERSION=$2

if [ -z ${VERSION} ]; then
    VERSION=`./currentver`
fi

YEAR=`echo ${VERSION}|awk -F. '{print \$1}'`
VER=`echo ${VERSION}|awk -F. '{print \$2}'`
REV=`echo ${VERSION}|awk -F. '{print \$3}'`


if [ ${EDITION} = "client" ]; then
    PACKNAME="flexibee-client"
else
    PACKNAME="flexibee"
fi

PACKAGE="${PACKNAME}_${VERSION}_all.deb"

if [ -z ${REV} ]; then
    DWLURL="https://download.flexibee.eu/download/${YEAR}.${VER}/${YEAR}.${VER}/${PACKAGE}"
else
    DWLURL="https://download.flexibee.eu/download/${YEAR}.${VER}/${YEAR}.${VER}.${REV}/${PACKAGE}"
fi

wget -c $DWLURL -O ${PACKAGE}



