#!/bin/sh
# postinst script for abraflexi-client
#

set -e

# Source debconf library.
. /usr/share/debconf/confmodule



# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package



case "$1" in
    configure)

        # Do you like debian?
	db_input high flexbee-client/UPDATEJASPER || true
	db_go

	# Check their answer.
	db_get flexbee-client/UPDATEJASPER
	if [ "$RET" = "true" ]; then
		/usr/share/abraflexi/bin/updatejasperclasspath 
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


exit 0
